version: '3.8'

services:

  redis:
    image: "redis:alpine"

  crawler:
    build: ${CRAWLER_BUILD}
    command: "uvicorn main:app --host 0.0.0.0 --port 8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  readable:
    build: ${READABLE_BUILD}
    command: "uvicorn api:app --host 0.0.0.0 --port 8002"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1

  embedder:
    build: ${EMBEDDER_BUILD}
    command: "uvicorn main:app --host 0.0.0.0 --port 8003"
    environment:
      - MODEL_PATH=${EMBEDDER_MODEL_PATH}
    volumes:
      - ${EMBEDDER_VOLUME}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  reranker:
    build: ${RERANKER_BUILD}
    command: "uvicorn main:app --host 0.0.0.0 --port 8004"
    environment:
      - RERANKER_MODEL=cross-encoder/ms-marco-MiniLM-L-6-v2
      - BATCH_SIZE=8
    ports:
      - "8004:8004"

  controller:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "80:8000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
      - crawler
      - readable
      - embedder
      - elasticsearch
      - reranker
    environment:
      - LOGGING_DIR=/app/logs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_INDEX=articles
      - ES_SEARCH_SIZE=25
      - EMBED_DIM=768
      - LLM_TEMPERATURE=0.5
      - CRAWLER_URL=http://crawler:8001/crawl
      - READABLE_URL=http://readable:8002/convert
      - EMBEDDER_URL=http://embedder:8003/embed_batch
      - RERANKER_URL=http://reranker:8004/rerank
      - OPENAI_API_KEY=${OPENAI_API_KEY}
