version: '3.8'

services:

  redis:
    image: "redis:alpine"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  controller:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "80:8000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
      - elasticsearch
    environment:
      - LOGGING_DIR=/app/logs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_INDEX=articles
      - ES_SEARCH_SIZE=50
      - EMBED_DIM=384
      - REFERENCE_SIZE=10
      - LLM_TEMPERATURE=0.7
      - CRAWLER_URL=https://fun-crawler-633f94e2f022.herokuapp.com/crawl
      - READABLE_URL=https://fun-readable-cd6ed9e43b50.herokuapp.com/convert
      - EMBEDDER_URL=https://fun-embedder-a83c86056e29.herokuapp.com/embed_batch
      - RERANKER_URL=https://fun-reranker-84b02fb456da.herokuapp.com/rerank
      - OPENAI_API_KEY=${OPENAI_API_KEY}
