version: '3.8'

services:

  redis:
    image: "redis:alpine"

  crawler:
    build: "/Users/rohan/1_Project/fun_crawler"
    command: "uvicorn main:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  readable:
    build: "/Users/rohan/1_Project/fun_readable"
    command: "uvicorn api:app --host 0.0.0.0 --port 8002"
    ports:
      - "8002:8002"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1

  embedder:
    build: "/Users/rohan/1_Project/fun_embedder"
    command: "uvicorn main:app --host 0.0.0.0 --port 8003"
    ports:
      - "8003:8003"
    environment:
      - MODEL_PATH=/models/all-mpnet-base-v2
    volumes:
      - /Users/rohan/3_Resources/ai_models/all-mpnet-base-v2:/models/all-mpnet-base-v2

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  controller:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - crawler
      - readable
      - embedder
      - elasticsearch
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_INDEX=articles
      - CRAWLER_URL=http://crawler:8001/crawl
      - READABLE_URL=http://readable:8002/convert
      - EMBEDDER_URL=http://embedder:8003/embed_batch
      - OPENAI_API_KEY=${OPENAI_API_KEY}
